#!/usr/bin/python3

if __name__ != '__main__':
    print("Must be run as main module")
    exit(1)

import importlib
import os
import sys

for function in os.listdir('src/functions'):
    sys.path.append(f'src/functions/{function}')

for layer in os.listdir('src/layers'):
    sys.path.append(f'src/layers/{layer}')


if len(sys.argv) != 3:
    print("Usage: locallambda <module name> <body>")
    exit(1)

module_name = sys.argv[1]
body = sys.argv[2]

lambda_module = importlib.import_module(module_name)
result = lambda_module.lambda_handler({'body': body}, None)
print(result)
