#!/usr/bin/python3

if __name__ != '__main__':
    print("Must be run as main module")
    exit(1)

import argparse
import json
import sys

sys.path.append(f'src/layers/rspfootball-util')

import rsputil
import rspmodel

DEFAULT_GAME = rspmodel.Game(
        gameId = 'test_default_id',
        version = 0,
        players = {
            'home': 'harry',
            'away': 'daylin',
        },
        state = rspmodel.State.PLAY_CALL,
        score = {
            'home': 0,
            'away': 0
        },
        penalties = {
            'home': 2,
            'away': 2
        },
        possession = 'home',
        firstKick = 'home',
        ballpos = 5,
        playCount = 1,
        down = 1,
        firstDown = 20,
        play = None,
        rsp = {
            'home': None,
            'away': None
        },
        roll = [],
        actions = {
            'home': ['CALL_PLAY', 'PENALTY'],
            'away': ['POLL']
        },
        result = [])

def set_game(overrides):
    game = {**DEFAULT_GAME.dict(), **overrides}

    rsputil.store_game(rspmodel.Game(**game))

parser = argparse.ArgumentParser(description='Update a game in DDB')
parser.add_argument('--json', default='{}', help='A json describing the desired game. If omitted, a default game is used')
parser.add_argument('overrides', nargs='*', default=[], help='Override default attributes. Should be in <key>=<value> form')

args = parser.parse_args()

overrides = json.loads(args.json)
for override in args.overrides:
    if '=' not in override:
        print("Unrecognized arg. Use <key>=<val> to override default attributes", file=sys.stderr)
        exit(1)
    key, val = override.split('=')
    overrides[key] = val

set_game(overrides)
